amir20/dozzle

- docker/client.go
- main.go
- main_test.go
- package.json
* Removes `context.Background()` that isn't really needed
* Returns channels instead
* Fixes zero containers
> Does a bunch of little cleanup

- assets/pages/Container.vue
Here are some comparison screenshots: https://imgur.com/a/LZ3OyL4. Using `white-space: pre-wrap` fixes the line wrap issue while preserving whitespace.
> Preserve whitespace

- .reflex
- README.md
- docker/client.go
- docker/client_test.go
- main.go
- main_test.go
Sometimes is quite handy to look upon `down` container logs, this PR make it possible.
It creates a `--showAll` flag, which by default set to `false`.
It will not break anything.
> added --showAll flag that will show all containers (default: false)

- README.md
This pull request adds a minimal sample Nginx config to the README.md file with the options that are required for getting Dozzle to work over HTTPS.
> Add sample Nginx config to README.md

- Dockerfile
Signed-off-by: Daniel Sutton <daniel@ducksecops.uk>
Node 13 becomes EOL on 1st June 2020, updating to Node 14 which is supported until 30th April 2023.
Excellent project keep up the good work.
> Updated dockerfile to node 14

- .gitignore
- README.md
Hi there :wave: Thanks for open sourcing this project! I was playing with the code and found a few minor things in the documentation that could have been a little clearer to me as a Go novice:
* Add links to the installation documentation for the various tools the project depends on.
* Make the CLI command to install reflex copy-pastable.
* I also ran into a pnpm user error which dropped a log file to disk which shouldn't be checked in so I added it to the git-ignore list to clean up the git status.
Hope that these minor changes can make it even easier for others to get started to contribute to the repository and thanks again!
> Improve setup documentation

- .github/workflows/dev.yml
- main.go
This pull request adds a new configuration option `DOZZLE_WAIT_FOR_DOCKER` which if set will defer the server start until the connection to docker is healthy.
In some environments, the docker connection isn't via a socket file but instead via tcp, for example if we're connecting to a remote docker host or if we're using a proxy to only allow selective access to docker APIs for security reasons. In these scenarios, the docker host may or may not be ready to serve requests at the time that dozzle starts. To simplify deployments in such an environment, it's very useful if dozzle can "self heal" and only start talking to the docker host once the docker host is ready for connections.
Of course it would also be possible to perform an external health check before starting the dozzle container, …
> Add option to wait for docker before starting

- assets/components/LogViewer/ComplexLogItem.vue
Noticed this issue when using the new json log lines feature. This should fix it. Now when you expand the json, it will say "collapse json" if it's still expanded.
> Fix json log line still says "expand json" when expanded

- README.md
Adds a FAQ point for #1965 where memory consumption wasn't shown on ARM devices.
> Update readme for memory consumption on ARM devices

- assets/components/LogViewer/LogViewer.vue
For the most part, this makes Safari use SF Mono instead of falling back to Consolas.
> Use ui-monospace as the default font for log viewer

- locales/de.yml
- locales/en.yml
- locales/es.yml
- locales/pr.yml
- locales/ru.yml
- locales/zh.yml
Removed the colon from the `<a>` tags in the "New version available" link, which prevented the URL from opening.
> Fix bad version update URL

- assets/composables/title.ts
- assets/layouts/default.vue
- assets/pages/container/[id].vue
- assets/pages/index.vue
- locales/de.yml
- locales/en.yml
- locales/es.yml
- locales/pr.yml
- locales/ru.yml
- locales/zh.yml
This PR improves the page title handling.
It fixes the following things:
* Add translations
* Add pluralization for the amount of running containers
* Prevent unnecessary updates by only setting the title when the data is fully loaded
* Set the correct title for the settings page when reloading
* A bug where the title would not change when switching from a container logs page to the dashboard
_Note_
I tried my best with the translations, but I do not know if they are all correct.
Google Translate gives me the right English translation back for each language.
> feat: Improve page title and add localization

- assets/modules/i18n.ts
Just a small improvement, close #2417
> Improve i18n support

- locales/zh-tw.yml
> feat: Add zh-tw locale

- Dockerfile
- assets/pages/index.vue
- assets/stores/config.ts
- auth/proxy.go
- main.go
- web/__snapshots__/web.snapshot
- web/csp.go
- web/healthcheck.go
- web/index.go
- web/routes.go
- web/version.go
See #2437 on discussion to create multi-user options for Dozzle. 
This is a start for saving all configuration on disk. 
This PR introduces `Remote-*` headers to associate each session with a user. 
```
Remote-Email: admin@example.com
Remote-Groups: admins,dev
Remote-Name: Admin
Remote-User: admin
```
To use this, set `DOZZLE_AUTH_PROVIDER` to `forward-proxy`. Here is an example from compose file I used for testing....
```
dozzle:
image: amir20/dozzle:latest    
networks:
- net
environment:
DOZZLE_AUTH_PROVIDER: forward-proxy
volumes:
- /var/run/docker.sock:/var/run/docker.sock  
labels:
- 'traefik.enable=true'
- 'traefik.http.routers.dozzle.rule=Host(`dozzle.example.com`)'
- 'traefik.http.routers.dozzle.entrypoints=https'
- 'traefik.http.routers.dozzle.tls=true'
- …
```
> feat: adds forward-proxy

- .gitignore
- assets/auto-imports.d.ts
- assets/components/LogViewer/LogEventSource.spec.ts
- assets/composables/eventsource.ts
- assets/layouts/default.vue
- assets/modules/router.ts
- assets/pages/login.vue
- assets/pages/settings.vue
- assets/stores/config.ts
- assets/stores/container.ts
- assets/stores/settings.ts
- internal/auth/proxy.go
- internal/profile/settings.go
- internal/web/index.go
- internal/web/profile.go
- internal/web/routes.go
- main.go
- vite.config.ts
For authenticated users, settings is now saved to `/data/[username]/settings.json`. This location will also be used for other user stuff like `savedSearch.json`. 
User should be able to do the following: 
1. Go to a browser and make sure there is a valid user signed in 
2. Make some changes to settings 
3. Go to a new browser that has never used Dozzle. Those settings should be copied over from server. 
4. If needed, `--volume /path/to/data:/data` is needed to persist settings between dozzle restart. However, Dozzle also stores content to `localStorage` so it will also sync localStorage.
> feat: syncs settings to disk for authenticated users

- assets/models/LogEntry.ts
This should fix #2451 where a json object has no payload.
> fix: fixes a potential rare edge case that log entry has no payload. see #2451.

- docs/.vitepress/config.ts
- docs/guide/custom-documentation.md
> docs: adds docs for custom content

- docs/guide/log-files-on-disk.md
Have expanded the `docker run` example for streaming log files from disk to include a `docker-compose.yml` option.
> docs: Add docker-compose.yml option

- README.md
The README is the only place to talk about a different host port than the container one (that is 8888 as the host port and 8080 as the container and application one).
Though the README sometimes tells the host port is 8888, sometimes 8080.
Make it 8888 in all cases.
The other documentation in the project uses the same port for hast and container so no need to change them.
> fix: make README container host port consistent

- locales/de.yml
- In german you can use "ihr/Ihr" or "du/Du" to refer to someone. Dozzles translation switches between both which is not a good way to do it. We should stay consistent with one variant.  ihr/Ihr is considered very formal while du/Du is considered more direct. Writing it with an uppercase start character is considered to be the more formal variant in both scenarios. In this commit all ihr/Ihr usages are replaced with "Du".
- some translations like 'running / total containers' were in the wrong form and got fixed. This is because containers refers to the plural so running and total need to refer to the plural as well.
- Some translations did not get fixed as I could not think of a better term. For instance, "AVG MEM" and "AVG CPU" would become to long "Durchschn. Speicher" or "Durchschn. …
> fix: update de.yml to use consistent wording and fix small issues

- assets/components/SideMenu.vue
I noticed that when hovering over a container in the side list with a health check the spacing would be thrown off when the pin container button appears.
**Before**
I resolved this by fixing the spacing of the grid so that it stays aligned. Additionally I swapped the pin button to be after the heath icon. This is so that the button stays in a consistent position, allow the user to move down an continue to pin if they need to. 
**After**
> fix: Icon placement when hovering over containers with health checks.

- assets/components/common/MobileMenu.vue
Updated the sidebar on the mobile to bring it closer to parity as the desktop. And fix some scrolling issues.
1. Updated the sidebar on mobile to show stopped containers
2. Sidebar either did not take the full height OR it overflowed and did not scroll on mobile. Both issues have been fixed by setting the height and overflow properties.
( FYI I hate CSS 😅 )
> fix: Updates to sidebar on mobile to align closer to desktop

- docs/guide/authentication.md
Updated authentication.md to utilize single quotes instead of double quotes for escaping the $ sign in passwords.
> docs: Update authentication.md

- docs/guide/authentication.md
- internal/auth/proxy.go
- internal/web/routes_proxy_test.go
- main.go
This PR adds support for Custom Headers for Forward Proxy-based Authentication. I've kept the defaults the same as the ones used currently.
I tested this PR with the following `docker-compose.yaml` and `Caddyfile`.
```
services:
dozzle:
image: amir20/dozzle:latest
restart: always
environment:
dozzle_auth_provider: forward-proxy
dozzle_auth_header_user: cf-access-authenticated-user-email
dozzle_auth_header_email: cf-access-authenticated-user-email
dozzle_auth_header_name: cf-access-authenticated-user-email
dozzle_no_analytics: true
volumes:
- /var/run/docker.sock:/var/run/docker.sock
ports:
- "8080:8080"
```
```
:3000 {
reverse_proxy http://localhost:8080 {
header_up Cf-Access-Authenticated-User-Email "ankit@test.com"
}
}
```
> feat: add support for custom headers for forward-proxy auth

- locales/en.yml
Further to discussion in https://github.com/amir20/dozzle/issues/2691 - slight tweak of wording to make it clearer that the switch will happen automatically unless the user clicks Cancel.
Also fixed a minor misspelling typo spotted in the file too!
> fix: reword message on similar container switch countdown banner

- README.md
Legacy auth is not supported anymore and is removed from the readme in this commit.
Supported env variables are synced with the current state.
> chore: adjust supported env variables in readme

- internal/docker/container_store.go
- internal/docker/stats_collector.go
- internal/utils/ring_buffer.go
- internal/utils/ring_buffer_test.go
- internal/web/events.go
This PR attempts to stop the background stat collector after 6 hours of idle time. The timer starts after the last client has disconnected.
> feat: deactivates collection of stats after 6 hours of idle

- docs/guide/remote-hosts.md
Fixed a minor path typo to avoid confusion (`/cert` to `/certs`)
Added a clarification to specify the host subfolder name expected. I spent some time wondering why my config wasn't working as my subfolder was named after the host label. 
It might be worth also adding to DEBUG logs when searching for certs in this subfolder. When debugging I saw that it couldn't find certs at the /certs location but there was no mention of the path it was looking for in /certs/hostIP so I didn't realise the path it expected didn't exist.
> docs: Updated documentation for Remote Host Setup

- internal/docker/host.go
Ran into this while figuring out why my remote host config wasn't working. Debug logging didn't tell me where it was expecting (and failing) to find the client certificate files, only that it didn't find them at the default `/certs` location. 
Existing debug log shows the final default path it looks for, but not the host-specific one it tries first. 
Added a debug log action to specify when this fails, where it expects the files to be.
> feat: Adding debug log when host-specific certificate path not found

- internal/docker/level_guesser.go
- internal/docker/level_guesser_test.go
My project generates structured JSON log messages with the `level` attribute having values of DEBUG, INFO, WARN, ERROR, etc <-- all in upper case. When viewed in dozzle, the purple/green/orange/red marker dots don't show for these entries. 
I tracked this down to the **level_guesser.go** file and noticed some missed test coverage. This PR should address that deficiency.
> fix: Coerce log level to lowercase when guessing in structured json

- docs/guide/faq.md
Added details relating to https://github.com/amir20/dozzle/issues/3015 that explain why 
and how the compression settings for traefik have to be adjusted to ensure logs flow correctly
> docs: Adjusting compression settings in Traefik

- assets/pages/settings.vue
- locales/de.yml
- locales/en.yml
Please check again whether I have included the variables correctly. I have never worked with `.vue` files before. The log has already been translated into German. I have not touched the other languages.
> feat: Translate the example log entries

- docs/guide/authentication.md
- go.mod
- go.sum
- internal/auth/users.go
See https://github.com/amir20/dozzle/security/advisories/GHSA-w7qr-q9fh-fj35
> feat: uses bcrypt hash instead

- internal/docker/level_guesser.go
- internal/docker/level_guesser_test.go
It's fairly common to have severity as the key for the log level. For example google cloud uses it. So this PR adds a check to check for the severity key if the level key is not found.
> fix: guess log level will also check severity

- docs/guide/faq.md
Include explanation of where all containers option is as referenced in #3221. 
Is there a way to do this via `docker run` and `docker compose` so those can be added to the FAQ as well? I saw there is a setting `showAllContainers:true` but am not sure how it should be added.
> docs: Add Show Stopped Containers to Dozzle

- assets/components/LogViewer/LogAnalytics.vue
When opening the SQL Analytics, it fetches all logs by default. On containers with many logs this can take a while. This PR changes the default by limiting it to first 100 log entries
> fix: limit default SQL log entries to 100

- assets/components/LogViewer/SimpleLogItem.vue
Following up on https://github.com/amir20/dozzle/pull/3353, this PR fixes a minor bug where HTML links are not shown with their normal color when using ANSI color escape sequences due to https://github.com/rburns/ansi-to-html inserting HTML tags inside `.log-wrapper`.
With:
```js
console.log(`${chalk.red('hi')} https://www.google.com ${chalk.green('world')}`);
```
Before:
After:
> fix: fix link color when using colorized logs

- internal/docker/logfmt.go
- internal/docker/logfmt_test.go
Hello, @amir20 and thank you for creating Dozzle! It’s a fantastic tool, and I really appreciate the effort you’ve put into developing it.
I recently encountered a crash with the following panic:
```
panic: runtime error: slice bounds out of range [222:221]
goroutine 260 [running]:
github.com/amir20/dozzle/internal/docker.ParseLogFmt({0x400060751f, 0x18c})
/dozzle/internal/docker/logfmt.go:23 +0x3f8
github.com/amir20/dozzle/internal/docker.createEvent({0x4000607500?, 0x1ac}, 0x113a7d0?)
/dozzle/internal/docker/event_generator.go:198 +0x50c
github.com/amir20/dozzle/internal/docker.(*EventGenerator).consumeReader(0x4000319ce0)
/dozzle/internal/docker/event_generator.go:95 +0x50
created by github.com/amir20/dozzle/internal/docker.NewEventGenerator in goroutine 215 …
```
> fix: fixes log parser

- .github/workflows/deploy.yml
I don't know if https://github.com/docker/metadata-action?tab=readme-ov-file#tags-input fail with 'v' prefix, I think not, but I used the 'raw' type because the result is the same after all and can be used w/o risk to changes on semver in future.
Closes #3549
> feat: add more tags to same release

- assets/components/LogViewer/SimpleLogItem.vue
This fixes wrong CSS variables being used for fallback colors, as daisyUI 5 changed them.
Note: no need for `oklch` anymore since they're now already in that format in main.css.
With the following code (using [chalk](https://github.com/chalk/chalk)):
```ts
console.log(chalk.bgRed('Hello') + ' World');
console.log(chalk.red('Hello') + ' World');
```
Before:
After:
> fix: fixes ansi-to-html fallback colors

- assets/App.vue
This sets the color of the tab bar to white to match the background color:
---
Updates #3703
> fix: use light mode bg color as theme color

- docs/guide/supported-env-vars.md
Examples were wrong, see
[#3523](https://github.com/amir20/dozzle/issues/3523) where tcp://1.2.3.4:7007 gets transformed into tcp://1.2.3.4:7007:443
Root cause: the endpoint values are passed to google golang grpc library, NewClient, which does not support "tcp://" prefix like other parts. Instead it supports
none, "dns://", "zookeeper://", "unix://", "unix-abstract://", "vsock:", "ipv4:", "ipv6:". In the future additional syntax might be added
See https://pkg.go.dev/google.golang.org/grpc#NewClient for GRPC documentation
and https://github.com/grpc/grpc/blob/master/doc/naming.md for possible values
> docs: remove leading tcp://

- .github/workflows/deploy.yml
- .github/workflows/test.yml
- internal/support/web/url.go
Dots are no longer allowed within URLs since https://github.com/amir20/dozzle/pull/4016.
This PR adjusts the regex to re-allow them inside URLs, but not at the end. See this page for examples:
https://regex101.com/r/GyEriu/4
Also took the opportunity to slightly clean up the regex by removing superfluous escapes.
Note: we could also optionally disallow `?` (question marks) at the end of URLs so that they're considered part of the sentence around it rather than the last char of the URL itself (even though it's technically valid).
Before:
After:
> fix: allows dots inside URLs (not at end)

- assets/components/ScrollableView.vue
Resolved an issue where hovering near the star button would trigger the copy tooltip, obstructing the UI when logs are displayed beneath the header
> fix: star conflicting with dropdown 

- docs/guide/k8s.md
The documentation currently states that Dozzle supports multiple namespaces via DOZZLE_NAMESPACES. In practice, multiple namespaces work when passed to DOZZLE_NAMESPACE as a comma-separated list. This PR updates the docs and examples to match the real behaviour.
Replaced references to DOZZLE_NAMESPACES with DOZZLE_NAMESPACE.
Users following the current docs will set DOZZLE_NAMESPACES and see no effect. Aligning the docs with actual behaviour prevents misconfiguration.
No breaking changes to running setups using DOZZLE_NAMESPACE.
Refs: https://github.com/amir20/dozzle/discussions/3614#discussioncomment-14102788
> docs: multiple namespaces use DOZZLE_NAMESPACE (comma-separated), not DOZZLE_NAMESPACES

- assets/components/Links.vue
- assets/stores/config.ts
- docs/guide/supported-env-vars.md
- internal/support/cli/args.go
- internal/web/index.go
- internal/web/routes.go
- main.go
Resolves #4090.
This PR adds an option (argument or env var) to disable avatars entirely.
If the option is set to true, a user icon will be displayed in the place of the avatar instead and the avatar route will be disabled.
> feat: implement ability to disable avatars

- internal/support/docker/docker_service.go
Fixes #4099 
When the attach event is triggered, the waitGroup counter is not incremented. So it panics and stops the backend when the websocket connection is closed. fixed by incrementing wg counter.
> fix: panic - waitGroup counter goes negative

- docs/guide/authentication.md
Working configuration for Pocket ID using oauth2-proxy container.
> docs: add SSO example for Pocket ID

- assets/components/Links.vue
- assets/stores/config.ts
- docs/guide/authentication.md
- docs/guide/supported-env-vars.md
- internal/support/cli/args.go
- internal/web/index.go
- internal/web/routes.go
- main.go
Adds support for a logout URL when using ForwarderProxy authentication in Dozzle. Users can now configure DOZZLE_AUTH_LOGOUT_URL to provide a custom logout endpoint.
Fixes https://github.com/amir20/dozzle/issues/4149#issuecomment-3339701720
> feat: add DOZZLE_AUTH_LOGOUT_URL support for ForwarderProxy
