assets/pages/Container.vue
Reverts amir20/dozzle#16
@iwittkau I am going to have to revert these changes because it looks like it break page wrap. Which is something that should work. I should have asked for a screenshot before merging.
=> Revert "assets/pages: preserve whitespace of log messages"

assets/pages/Container.vue, package-lock.json, package.json
=> Adds ansi colors via ansi-to-html

README.md, docker/client.go, docker/client_test.go, main.go
can be used with `--filter foo=bar` or `DOZZLE_FILTER=foo=bar`
=> Adds filters to be used with all supported filters

README.md
=> Add filter usage hints

assets/components/InfiniteLoader.vue, assets/components/LogEventSource.spec.js, assets/components/LogEventSource.vue, assets/components/LogViewer.vue, assets/components/LogViewerWithSource.vue, assets/components/ScrollableLogsWithSource.vue, assets/components/ScrollableView.vue, assets/components/__snapshots__/LogEventSource.spec.js.snap, assets/pages/Container.vue, assets/styles.scss, docker/client.go, main.go, package-lock.json, package.json
Starts the implementation of #200
=> Fetch more

README.md
=> fix filter syntax

.github/workflows/push.yml, assets/components/LogEventSource.spec.js, assets/components/LogViewer.vue, assets/pages/Settings.vue, assets/store/settings.js
=> Adds settings for timestamp. Fixes #360

assets/components/LogEventSource.spec.js, assets/components/LogEventSource.vue
=> support more timestamp formats

Dockerfile
=> Revert "Updated dockerfile to node 14"

assets/App.vue, assets/components/LogViewer.vue, assets/components/SideMenu.vue, assets/pages/Index.vue, assets/pages/Settings.vue, assets/store/settings.js, assets/styles.scss
Hello!
Please consider reviewing my PR which introduces an option to switch to a light-theme.
Implemented new settings toggle button which allows us to switch between the original Dozzle theme and a light-theme.
Thank you so much,
Catalin MUNTEANU
=> added support for toggling between new light theme and dark theme.

assets/components/ScrollProgress.vue, assets/components/ScrollableView.vue, assets/index.ejs, package.json, yarn.lock
This is still work in progress, but I am doing a circular progress bar to show how much has been scrolled. I have found this useful personally.
=> Adds progress notification  bar

assets/App.vue, assets/components/InfiniteLoader.vue, assets/components/LogContainer.vue, assets/components/LogEventSource.vue, assets/components/LogViewerWithSource.vue, assets/components/MobileMenu.vue, assets/components/ScrollProgress.vue, assets/components/ScrollableView.vue, assets/pages/Container.vue, assets/pages/Index.vue
Also did some refactoring of code.
=> Changes scroll progress to behave differently when fetching scroll back content. 

assets/components/LogEventSource.spec.js, assets/components/LogEventSource.vue, docker/client.go
=> Keep spaces. Maybe fixes #838

docker/client.go, main.go
See https://github.com/alexflint/go-arg/issues/155 and should fix bug in #293
=> Adds separate options for filter. 

README.md, assets/App.vue, assets/components/LogViewer.vue, assets/composables/settings.ts, assets/pages/Settings.vue, assets/styles.scss
=> Add auto mode for colorscheme

README.md, main.go, web/auth.go, web/routes.go, web/routes_test.go
=> Auto session storage key

web/logs.go
Adds a simple heartbeat to fix timeout errors. Fixes #1831.
=> Adds a heartbeat for log stream

.gitignore, assets/App.vue, assets/components.d.ts, assets/components/ContainerStat.vue, assets/components/ContainerTitle.vue, assets/components/FieldList.vue, assets/components/InfiniteLoader.vue, assets/components/JSONPayload.vue, assets/components/LogActionsToolbar.vue, assets/components/LogContainer.vue, assets/components/LogEventSource.spec.ts, assets/components/LogEventSource.vue, assets/components/LogViewer.vue, assets/components/LogViewerWithSource.vue, assets/components/ScrollableView.vue, assets/components/__snapshots__/LogEventSource.spec.ts.snap, assets/composables/eventsource.ts, assets/composables/search.ts, assets/composables/visible.ts, assets/styles.scss, assets/types/Container.d.ts, assets/types/LogEntry.d.ts, assets/types/VisibleLogEntry.ts, assets/utils/index.ts, docker/types.go, package.json, pnpm-lock.yaml, tsconfig.json, web/__snapshots__/web.snapshot, web/logs.go
This pull request adds JSON support.
=> Support for JSON logs

assets/components.d.ts, assets/components/FuzzySearchModal.vue, assets/components/InfiniteLoader.vue, assets/components/LogActionsToolbar.vue, assets/components/LogViewer/ComplexLogItem.vue, assets/components/LogViewer/FieldList.vue, assets/components/LogViewer/LogContainer.vue, assets/components/LogViewer/LogViewer.vue, assets/components/PastTime.vue, assets/components/RelativeTime.vue, assets/components/ScrollProgress.vue, assets/components/ScrollableView.vue, assets/pages/container/[id].vue
- Tries to clean up defineprops
- Cleans up define props for all components
=> Cleans up define props with typescript and cleans up css

docker/calculation.go, docker/calculation_test.go, docker/client.go
Based on discussion with @amir20 prepared small fix presentation of memory consumption.
Closes https://github.com/amir20/dozzle/issues/1891
=> Change calculation of memory usage.

assets/components.d.ts, assets/components/LogViewer/ContainerStat.vue, assets/components/LogViewer/StatSparkline.vue, assets/types/Point.d.ts, package.json, pnpm-lock.yaml
- Updates modules
- Cleans up stats
=> stat cleanup

locales/ru.yml
Signed-off-by: Dmitry Mazurov <dimabzz@gmail.com>
=> Add ru locale

assets/components/MobileMenu.vue, assets/layouts/default.vue, assets/pages/index.vue
Added search, setting and logout button inside mobile menu
=> Update mobile menu

README.md, analytics/types.go, docker/client.go, docker/client_test.go, main.go, web/logs.go, web/routes.go, web/routes_test.go
Removing `tailsize` as it isn't used and default 300 should be ok for everybody.
=> Removes tail size

package.json, pnpm-lock.yaml
=> Revert "Update dependency vitepress to v1.0.0-alpha.52"

assets/components.d.ts, assets/components/LogViewer/LogLevel.vue, assets/components/SideMenu.vue, assets/models/Container.ts, assets/pages/index.vue, assets/stores/container.ts, assets/styles.scss, assets/types/Container.d.ts, docker/client.go, docker/types.go, web/events.go
Adds healthcheck test by looking status value.
=> Adds health status by parsing the label from status

assets/components.d.ts, assets/components/LogViewer/ContainerTitle.vue, assets/components/SideMenu.vue
=> Adds tooltip to healthcheck. Fixes #2104

assets/components/SideMenu.vue
=> feat: sorts running conttainers at top

assets/components/LogViewer/ContainerTitle.vue, assets/components/SideMenu.vue, assets/models/Container.ts
=> feat: makes swarm id lighter

assets/components/MobileMenu.vue
- Revert "feat: adds host drop down to mobile view. see #2157 (#2160)"
- feat: moves mobiles host drop down to mobile menu
=> feat: moves mobile host to mobile menu. see #2157

package.json, pnpm-lock.yaml, tsconfig.json, vite.config.ts
- chore: updates node modules
- chore: fixes reactivity warning
=> vue updates

locales/zh.yml
Original english translations at https://github.com/amir20/dozzle/blob/master/locales/en.yml
=> feat: adds chinese translations

docker/client.go, main.go, main_test.go, web/routes.go, web/routes_auth_test.go, web/routes_logs_test.go
- feat: removes localhost as a required connection
- refactors code
=> no default client

web/events.go
fix: improves performance by making initital requests in parallel
=> fix: improves performance by making initital requests in parallel

docker/event_generator.go, docker/event_generator_test.go
- chore: cleans waitgroups
- chore: adds benchmark
=> go cleanup

assets/auto-imports.d.ts, assets/components.d.ts, assets/components/LogViewer/DockerEventLogItem.vue, assets/components/common/TimedButton.vue, assets/composables/settings.ts, assets/composables/toast.ts, assets/layouts/default.vue, assets/main.css, assets/pages/settings.vue, assets/stores/container.ts, locales/de.yml, locales/en.yml, locales/es.yml, locales/pr.yml, locales/ru.yml, locales/zh.yml
- feat: implements a toast for alerting errors and other useful information
- removes unused code
- feat: adds automatic redirect when a new container is found
=> feat: adds automatic redirect when a new container is found

docker/event_generator.go
- fix: fixes reading incorrect number of bytes. see #2431
=> fix: fixes reading incorrect number of bytes. see #2431

assets/auto-imports.d.ts, assets/components/common/DateTime.vue
=> feat: makes hour time format always 2 digits

Dockerfile
=> fix: fixes not being able to create /data dir

internal/web/index.go
A good problem to have is a lot of data. But a bad problem is to store this data some where. According to Google Analytics, I get 100s of thousands of session per hour. This is too much data for GA so I am going to remove this. Maybe I will have a better solution in the future.
=> feat: removes request analytics on page load

README.md
added the section in README.md, how to install dozzle on podman
=> docs: installation on podman

internal/auth/users.go
=> fix: fixes proxy pass not finding user

docs/guide/authentication.md
looks like the authentication is case sensitive.
=> docs: update authentication.md 

assets/auto-imports.d.ts, assets/components/Links.vue, assets/components/LogViewer/ContainerTitle.vue, assets/components/SideMenu.vue, assets/composable/persistedStorage.ts, assets/composable/profileStorage.ts, assets/composable/storage.ts, assets/stores/config.ts, assets/stores/settings.ts, internal/profile/disk.go, internal/web/index.go, internal/web/profile.go, internal/web/routes.go
=> feat: syncs all profile localStorage to disk

assets/components/LogViewer/ContainerTitle.vue
=> fix: moves favorite star to the left and healthcheck to the right of container name

internal/docker/client.go, internal/docker/client_test.go, internal/web/container_actions.go, internal/web/routes.go, internal/web/routes_actions_test.go, internal/web/routes_test.go
Hi @amir20 ! Sorry for delay, as i was looking at test packages documentation for reference 😅.
I have almost covered the critical functions.
=> test: added test cases for container actions

docs/guide/supported-env-vars.md
Added "Container Actions" to table.
=> docs: Update supported-env-vars.md

assets/components/LogViewer/ComplexLogItem.vue, assets/components/LogViewer/SimpleLogItem.vue, assets/components/LogViewer/__snapshots__/LogEventSource.spec.ts.snap
=> fix: actions on log UI issues

assets/components/LogViewer/SimpleLogItem.vue, package.json, pnpm-lock.yaml
=> fix: copy log ansi character parsing and html decode

assets/pages/settings.vue, package.json, pnpm-lock.yaml, tailwind.config.ts
- feat: uses container queries to improve panels
- improves settings page
=> chore: enables container queries 

assets/components/common/DateTime.vue
=> fix: fixes 24 hour style being broken on chrome. fixes #2680

assets/pages/settings.vue
=> chore: makes faked data better.

locales/es.yml
=> Update locale es.yml

docker-compose.yml
docker.sock should be read only.
https://github.com/amir20/dozzle/issues/2697
=> read only docker.sock

assets/components/ContainerTable.vue, assets/components/common/DropdownMenu.vue
=> feat: adds option to home page to show more than default containers per page

internal/docker/client.go, internal/docker/container_store.go, internal/docker/event_generator.go, internal/docker/stats_collector.go, internal/web/events.go
- fix: improves logging
- adds close channels
- fix: fixes a potential deadlock when reading stats
=> fix: fixes a potential deadlock when reading stats

internal/docker/client.go, internal/web/logs.go
=> fix: fixes missing nano seconds for parsing between logs. see #2783

docs/guide/changing-base.md
Thank you, Amir, for your awesome work!
I submit the two necessary modifications I made in order to provide Dozzle in a subroute of my site.
=> docs: add missing base slash and remove non-existent nginx configuration

locales/fr.yml
=> feat: Adds french 

assets/components.d.ts, assets/components/LogViewer/ComplexLogItem.vue, assets/components/LogViewer/FieldList.vue, package.json, pnpm-lock.yaml
- **feat: improves collapse for complex queries**
- **feat: improves icons placement for expanding json**
=> feat: improves icons placement for expanding json

assets/components/FuzzySearchModal.vue, assets/components/LogViewer/DockerEventLogItem.vue, assets/pages/index.vue
Fixes https://github.com/amir20/dozzle/issues/2885
=> fix: removes toSorted() for older browsers that do not support it

locales/tr.yml
- **Create tr.yml**
- **feat: Add Turkish language support**
=> feat: Add Turkish language support

assets/components/ContainerTable.vue
=> feat: sorts homepage every 10 seconds

locales/fr.yml
small update to reflect "en" changes
=> fix: updates fr.yml

locales/da.yml
Translations done by a Danish citizen
=> feat: Danish translation file

assets/stores/container.ts
=> fix: only shows event stream error when trying to reconnect

internal/docker/event_generator.go, internal/docker/event_generator_test.go, internal/docker/level_guesser.go, internal/docker/level_guesser_test.go
=> fix: fixes nil pointer when message is null

assets/components/FuzzySearchModal.vue
=> feat: display top 10 in fuzzysearch

assets/components/FuzzySearchModal.spec.ts, assets/components/FuzzySearchModal.vue
Fixes #3017 
https://github.com/amir20/dozzle/assets/260667/70231679-91e9-475a-ae66-14a236b0a2fe
=> feat: improves search by showing all matches within threshold and enable scrolling instead

assets/components/LogViewer/LogLevel.vue, internal/docker/level_guesser.go
Added the critical log level (used by e.g. Python logging module)
=> feat: adds critical

Dockerfile, internal/analytics/types.go, internal/support/cli/analytics.go, internal/support/cli/args.go, internal/support/cli/clients.go, main.go
- **chore: refactors main.go and moves cli args to a new file**
- **chore: refactors main.go and moves cli args to a new file**
=> chore: refactors main.go and moves cli args to a new file

internal/agent/server.go, internal/docker/event_generator.go, internal/docker/event_generator_test.go, internal/support/docker/client_service.go, internal/support/docker/multi_host_service.go, internal/web/routes.go, package.json
=> fix: improves memory leak in new container stream

internal/agent/client.go, internal/support/docker/multi_host_service.go, internal/web/routes.go
=> fix: properly closes unused connections

docs/guide/supported-env-vars.md, docs/guide/swarm-mode.md
=> docs: updates docs

assets/stores/swarm.ts
Fixes https://github.com/amir20/dozzle/issues/3093
=> feat: sorts services in swarm view

assets/stores/container.ts, internal/web/__snapshots__/web.snapshot, internal/web/events.go
- **feat: removes orphaned containers. fixes #3077**
- **fixes tests**
=> feat: removes orphaned containers. fixes #3077

assets/components/HostMenu.vue, assets/stores/container.ts, assets/types/Container.d.ts
=> fix: fixes broken auto redirect. see #3123

assets/components/InfiniteLoader.vue, assets/components/LogViewer/EventSource.vue, assets/composable/eventStreams.ts
=> fix: fetching more should only allow for one and abort if one is already in progress. fixes #3113

internal/docker/client.go, internal/docker/client_test.go
=> fix: fixes first few lines not showing up. fixes #3139

internal/agent/client.go, internal/support/docker/agent_service.go, internal/support/docker/client_service.go, internal/support/docker/multi_host_service.go, internal/support/docker/retriable_client_manager.go, internal/support/docker/swarm_client_manager.go
=> fix: refreshes versions for agent properly after restart

docs/guide/actions.md
Fix the syntax when enabling Actions with a compose file
=> docs: Fix syntax to enable actions

assets/composable/eventStreams.ts, assets/composable/search.ts
Fixes https://github.com/amir20/dozzle/issues/3178
=> fix: fixes search skipping every other log

assets/components.d.ts, assets/components/GroupedViewer/GroupedLog.vue, assets/components/LogViewer/MultiContainerActionToolbar.vue, assets/components/ServiceViewer/ServiceLog.vue, assets/components/StackViewer/StackLog.vue, internal/docker/client.go
=> feat: adds action toolbar for groups, services and stacks

examples/docker.agents-with-certs.yml, examples/docker.swarm.yml, internal/support/cli/certs.go
=> feat: reads certs locally if available

README.md
=> fix: host port nb typo in readme

Makefile, assets/composable/eventStreams.ts, internal/utils/ring_buffer.go, internal/web/__snapshots__/web.snapshot, internal/web/logs.go, internal/web/logs_test.go
Fixes https://github.com/amir20/dozzle/issues/3222
=> feat: retries to fetch more logs if no logs are fetched when scrolling up

assets/components/LogViewer/LogList.vue, assets/components/LogViewer/__snapshots__/EventSource.spec.ts.snap, assets/components/ScrollProgress.vue, assets/components/ScrollableView.vue, assets/composable/logContext.ts, assets/composable/scrollContext.ts
- **WIP**
- **adds code**
- **more clean up**
- **clean up date**
=> feat: changes scroll progress to reflect total available logs instead of just the logs in the browser

assets/components.d.ts, assets/components/LogViewer/ComplexLogItem.vue, assets/components/LogViewer/LogDetails.vue
=> feat: shows raw json in complex logs with option to copy

assets/auto-imports.d.ts, assets/components.d.ts, assets/components/ContainerViewer/ContainerActionsToolbar.vue, assets/components/LogViewer/EventSource.spec.ts, assets/composable/eventStreams.ts, assets/composable/logContext.ts, assets/models/LogEntry.ts, internal/docker/level_guesser.go, internal/docker/level_guesser_test.go, internal/web/logs.go, locales/en.yml
Fixes https://github.com/amir20/dozzle/issues/2432
=> feat: adds support for levels

docs/guide/authentication.md, internal/auth/simple.go, internal/support/cli/args.go, internal/web/auth.go, internal/web/auth_simple_test.go, internal/web/routes.go, main.go
Fixes https://github.com/amir20/dozzle/issues/3309
=> feat: supports auth ttl to override session with DOZZLE_AUTH_TTL env.

internal/docker/event_generator.go
Fixes https://github.com/amir20/dozzle/issues/3323
=> fix: fixes empty blank links to not show up as json

assets/components/LogViewer/LogList.vue, assets/components/LogViewer/__snapshots__/EventSource.spec.ts.snap, assets/components/common/Tag.vue
Fixes https://github.com/amir20/dozzle/issues/3331
=> feat: removes rounded corners in compact mode

internal/docker/container_store.go, internal/web/auth_test.go, internal/web/debug.go, internal/web/routes.go
Fixed https://github.com/amir20/dozzle/issues/3337
=> fix: fixes an edge case where a container might get stuck in created state

assets/components/LogViewer/LogDetails.vue, assets/models/LogEntry.ts
Fixes https://github.com/amir20/dozzle/issues/3339
=> fix: fixes toggle all when fields have not been set for JSON

internal/web/healthcheck.go
Fixes https://github.com/amir20/dozzle/issues/3358
=> feat: skips healthcheck for agents

assets/composable/eventStreams.ts, internal/web/logs.go
=> fix: fixes pagination when logs are very long packed together. see #3373

internal/web/logs.go
Fixes https://github.com/amir20/dozzle/issues/3383
=> fix: fixes broken minimum logs. see #3383

assets/models/Container.ts, assets/stores/container.ts, internal/docker/client.go, internal/docker/container_store.go, internal/docker/types.go, internal/web/__snapshots__/web.snapshot, internal/web/events.go
Fixes https://github.com/amir20/dozzle/issues/3389
=> feat: supports container rename

assets/components/LogViewer/ComplexLogItem.vue, internal/docker/level_guesser.go
Fixes https://github.com/amir20/dozzle/issues/3397
=> fix: fixes log levels that have ansi color by stripping

README.md, docs/guide/faq.md, docs/guide/podman.md
New documentation explains the host not found error happening on Podman and shows steps to resolve the error.
=> docs: Add podman.md in docs, adjust readme.md/faq.md with host not found error documentation

assets/components/LogViewer/EventSource.spec.ts, assets/components/LogViewer/EventSource.vue, assets/components/LogViewer/__snapshots__/EventSource.spec.ts.snap
Fixes https://github.com/amir20/dozzle/issues/3386
=> feat: adds a short delay while waiting for logs to show

assets/components/LogViewer/LogAnalytics.vue
- Added classes `max-h-48`, `overflow-y-auto`, and `pr-2` to the label container.
- Ensured proper handling of overflowing content with vertical scroll support.
- Improved padding for better alignment.
=> fix(#3347): Improve label styling in scrollable container resolve #3347

examples/docker.swarm.yml, internal/support/docker/multi_host_service.go, internal/support/docker/retriable_client_manager.go, internal/support/docker/swarm_client_manager.go, internal/web/healthcheck.go
Fixes https://github.com/amir20/dozzle/issues/3420
=> feat: improves healthcheck for swarm nodes

docs/guide/agent.md, docs/guide/authentication.md, docs/guide/filters.md, internal/auth/proxy.go, internal/auth/simple.go, internal/auth/users.go, internal/docker/types.go, internal/support/cli/args.go, internal/web/auth_proxy_test.go, internal/web/events.go, internal/web/logs.go, main.go
Fixes https://github.com/amir20/dozzle/issues/3439
=> feat: allows filters to be set at user level

.github/workflows/deploy.yml, .github/workflows/dev.yml, docs/guide/getting-started.md
Fixes https://github.com/amir20/dozzle/issues/3483
=> feat: deploys to ghcr

assets/components/LogViewer/LogLevel.vue, internal/docker/level_guesser.go, internal/docker/level_guesser_test.go
Fixes https://github.com/amir20/dozzle/issues/3478
=> fix: fixes log levels not being parsed correctly and supports short levels like dbg

assets/components/LogViewer/ContainerEventLogItem.vue, assets/models/LogEntry.ts
Fixes https://github.com/amir20/dozzle/issues/3473
=> fix: shows container and host name correctly for events.

internal/docker/level_guesser.go, internal/docker/level_guesser_test.go
This aims to resolve issue https://github.com/amir20/dozzle/issues/3516
=> feat: handle log levels with double quotes

internal/docker/event_generator.go, internal/docker/types.go
=> fix: fixes grouping not working with unknown levels

main.go
Fixes https://github.com/amir20/dozzle/issues/3515
=> fix: fixes hostname feature for swarm mode

assets/components/FuzzySearchModal.vue
Fixes https://github.com/amir20/dozzle/issues/3539
=> fix: fixes unclickable items in search

assets/components/LogViewer/LogItem.vue, assets/components/LogViewer/RandomColorTag.vue
Fixes https://github.com/amir20/dozzle/issues/3563
=> fix: only truncate right the container name and not hostname

assets/components.d.ts, assets/components/GroupMenu.vue, assets/components/GroupsMenu.vue, assets/components/SideMenu.vue, assets/components/SwarmMenu.vue, assets/pages/container/[id].vue, assets/pages/group/[name].vue, assets/pages/host/[id].vue, assets/pages/merged/[ids].vue, assets/pages/service/[name].vue, assets/pages/stack/[name].vue, locales/da.yml, locales/de.yml, locales/en.yml, locales/es.yml, locales/fr.yml, locales/it.yml, locales/pl.yml, locales/pr.yml, locales/ru.yml, locales/tr.yml, locales/zh-tw.yml, locales/zh.yml
Fixes https://github.com/amir20/dozzle/issues/3574
=> feat: adds new menu for custom groups

docker-compose.yml, internal/container/container_store.go, internal/container/stats_collector.go, internal/docker/client.go, internal/support/cli/args.go
See https://github.com/docker/for-mac/issues/7575
=> fix: updates default timeout and adds user agent. see #3610

internal/support/cli/clients.go, main.go
Fixes https://github.com/amir20/dozzle/issues/3626
=> fix: fixes broken nil pointer. fixes #3626

internal/container/container_store.go, internal/container/types.go, internal/docker/client.go, internal/k8s/client.go, internal/k8s/stats_collector.go, internal/support/cli/args.go, main.go
Fixes https://github.com/amir20/dozzle/issues/3630
=> feat: supports namespaces properly in k8s mode

internal/k8s/client.go
See https://github.com/amir20/dozzle/issues/3646
=> fix: Removes streams from k8s. See #3646

internal/web/actions.go
Fixes https://github.com/amir20/dozzle/issues/3662
=> fix: uses request context instead of timeout for actions

internal/container/container_store.go, internal/docker/client.go
See https://github.com/amir20/dozzle/issues/3667#issuecomment-2679497775
=> chore: adds warning log if containers are empty using user filter

assets/auto-imports.d.ts, internal/web/logs.go
Fixes https://github.com/amir20/dozzle/issues/3687
=> fix: fixes analytics tab when mixed logs are found

assets/App.vue, public/index.html, public/manifest.webmanifest
Fixes https://github.com/amir20/dozzle/issues/3703
=> fix: fixes theme color in dark and light mode

locales/zh-tw.yml
It's now aligned with the latest English locale :tada:
=> fix: Update and improve zh-tw Traditional Chinese locale

assets/components/ContainerViewer/ContainerActionsToolbar.vue, assets/stores/config.ts, internal/support/cli/args.go, internal/web/index.go, internal/web/routes.go, main.go
Fixes https://github.com/amir20/dozzle/issues/3732#issuecomment-2767002802
=> feat: adds shell behind a flag or env var

docs/guide/changing-base.md
update  nginx websocket config example
=> fix(docs): update nginx websocket config example

internal/container/container_store.go
Fixes https://github.com/amir20/dozzle/issues/3824
=> fix: fixes potential nil pointer when no container exists

internal/container/event_generator.go, internal/support/search/search.go, internal/support/web/escape.go, internal/web/logs.go
Fixes https://github.com/amir20/dozzle/issues/3831
=> fix: fixes searching escaped html and by unescaping before searching

internal/web/__snapshots__/web.snapshot, internal/web/index.go
Fixes https://github.com/amir20/dozzle/issues/3844#issuecomment-2828978075
=> fix: adds html content type to index.html

assets/components/LogViewer/MultiContainerStat.vue
Fixes https://github.com/amir20/dozzle/issues/3836
=> fix: fixes total limit memory with multiple containers on the same host

locales/nl.yml
This update adds Dutch language support to Dozzle, expanding its multilingual capabilities. It includes translations for various UI elements such as buttons, tooltips, labels, and settings, allowing Dutch-speaking users to interact with Dozzle in their native language.
A minor linter issue was identified on line 42, specifically with the text `logs-skipped: {total} items overgeslagen`. This was resolved by escaping the placeholder, changing it to `logs-skipped: \{total} items overgeslagen`, ensuring that the linter issue is resolved.
=> feat: Add Dutch Translation (I18N) Support

locales/id.yml
This pull request adds support for the Indonesian language (Bahasa Indonesia) to Dozzle's internationalization system.
- Added `id.yml` file with complete Indonesian translations.
As part of an upcoming event focused on container monitoring tools, Dozzle will be featured as one of the highlighted applications. Having an Indonesian translation will make it more accessible to local attendees and help promote wider adoption of Dozzle in the region.
Thank you for building and maintaining this great tool!
=> feat(i18n): add Indonesian translation

docs/guide/agent.md, docs/guide/remote-hosts.md
Hi there,
Added a bit more description to the Agents and the Remote hosts pages. Feel free to edit and give feedback!
Thanks
Steven
=> docs(Agents): Add more explanations about Socket Proxies and agents

assets/components/common/RelativeTime.vue
Fixes https://github.com/amir20/dozzle/issues/3898
=> fix: fixes broken relative time in scroller

assets/components/common/DropdownMenu.vue, assets/components/common/LabeledInput.vue, assets/pages/container/[id].vue, assets/pages/settings.vue, assets/stores/settings.ts, internal/profile/disk.go
Fixes https://github.com/amir20/dozzle/issues/3895 and https://github.com/amir20/dozzle/discussions/3538.
=> feat: adds option to instantly redirect to new container

assets/components.d.ts, assets/components/ContainerViewer/ContainerActionsToolbar.vue, assets/components/HostMenu.vue, assets/components/LogViewer/MultiContainerActionToolbar.vue, assets/components/SwarmMenu.vue, assets/components/common/DropdownMenu.vue, locales/en.yml
Fixes https://github.com/amir20/dozzle/issues/3927
=> feat: adds a option to collapse all in side menu 

locales/nl.yml
This pull request improves the Dutch translation of the help support message in the `nl.yml` file.
What Was Changed?
- Updated the text under `settings: help-support` to improve tone and clarity.
- Rephrased the message to sound more natural and professional to Dutch-speaking users.
```yml
Please support Dozzle by donating or sponsoring us on GitHub. Your contributions help us improve Dozzle for everyone. Thank you! 🙏🏼
```
```yml
Support Dozzle by donating or sponsoring us on GitHub. Your contribution helps us improve Dozzle for everyone. Thank you! 🙏🏼
```
<br />
> [!NOTE]
> This is the translated English equivalent of the actual Dutch message update.
The previous Dutch translation included stylistic issues and felt less natural to native speakers. The revised version reads more fluently …
=> fix: Improve Dutch translation for help support message in nl.yml

locales/ko.yml
This pull request adds Korean 🇰🇷 (한국어) support.
* Added ko.yml file with complete Korean translations
Wrote translations with a focus on clarity, brevity, and user-centered tone.
Avoided literal translation to ensure natural, intuitive phrasing for Korean users.
I hope this contribution is helpful to the community! 😊
도즐 많이 이용해주세요! (Hope many people enjoy using Dozzle!)
=> feat(i18n): add Korean translation

docs/guide/authentication.md
Saw a small typo in the docs which makes the command fail, and wanted to contribute to the project !
If there are other requirements for the PR, I'll implement them if needed :)
=> docs: remove superfluous run in docker command

internal/support/docker/multi_host_service.go
See https://github.com/amir20/dozzle/issues/4087
=> feat: Changes the fetching of containers from serial to parallel.

internal/agent/client.go
Fixes https://github.com/amir20/dozzle/issues/4160
=> feat: adds compression and bigger receive limit to agent grpc
